steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    id: Push latest image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --ingress
      - all
      - --allow-unauthenticated
      - --service-account
      - ${_SERVICE_ACCOUNT}
      - --min-instances=0
      - --max-instances=1
      - --port
      - "8080"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _AR_REPO: app-images
  _IMAGE_NAME: mke-property-rag-query-service
  _SERVICE_NAME: mke-property-rag-query-service
  _SERVICE_ACCOUNT: